name: build
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Lint & test
        id: check
        continue-on-error: true
        run: ./gradlew --no-daemon clean check --continue

      - name: Generate JaCoCo coverage report
        id: jacoco
        if: always()
        run: ./gradlew --no-daemon jacocoTestReport -x test

      - name: Build jars
        if: always()
        run: ./gradlew --no-daemon assemble

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: libs-${{ github.run_number }}
          path: build/libs/*.jar
          if-no-files-found: warn

      - name: Upload test & lint reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ github.run_number }}
          path: |
            build/reports/**
            build/test-results/**
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ github.run_number }}
          path: |
            build/reports/jacoco/test/**
            build/jacoco/test.exec
          if-no-files-found: warn
          retention-days: 7

      # Make the job fail overall if tests failed
      - name: Fail if checks or coverage failed
        if: ${{ steps.check.outcome == 'failure' || steps.coverage.outcome == 'failure' }}
        run: exit 1
